---
- import_playbook: /opt/app/build.yaml

- name: Create container in docker server and run
  hosts: docker_server
  gather_facts: false

  tasks:
    - name: Pull mw-image from registry and run a container
      docker_container:
        name: mw-container1
        image: mrh13j/repo:latest
        state: started
        recreate: yes
        detach: true
        pull: yes
        ports:
          - "80:8080"
#    - name: Pull mw-image from registry and run a container
#      docker_container:
#        name: mw-container2
#        image: mrh13j/repo:latest
#        state: started
#        recreate: yes
#        detach: true
#        pull: yes
#        ports:
#          - "81:8081"
#    - name: Pull mw-image from registry and run a container
#      docker_container:
#        name: mw-container3
#        image: mrh13j/repo:latest
#        state: started
#        recreate: yes
#        detach: true
#        pull: yes
#        ports:
#          - "82:8082"
